function K = covIMT1(hyp, x, z, i)

% Integrated MT3
%
% k(x,y) = xxx
%
% where the hyperparameters are:
%
% hyp = [ log(l)
%         location ]
%
% Copyright (c) by James Robert Lloyd, 2013-08-05.

%%%% Warning - assumes 1d x and z

if nargin<2, K = '3'; return; end                  % report number of parameters
if nargin<3, z = []; end                                   % make sure, z exists
xeqz = numel(z)==0; dg = strcmp(z,'diag') && numel(z)>0;        % determine mode

n = size(x,1);
l = exp(hyp(1));
location = hyp(2);
sf2 = exp(2*hyp(3));

if dg
    a = x - location;
    b = x - location;
else
    if xeqz 
        a = repmat(x - location, 1, n);
        b = a';
    else
        a = repmat(x - location, 1, length(z));
        b = repmat((z - location)', length(x), 1);
    end
end

if nargin<4                                                        % covariances
    % This is numerically unstable for large a and b
    % Need to change it
    K = ((a > 0) & (b >= a)) .* ...
        l.*(2*a-l*exp(-(a+b)/l).*(-1+exp(a/l)).*(exp(a/l)+exp(b/l)))...
        +...
        ((b > 0) & (a > b)) .* ...
        l.*(2*b-l*exp(-(b+a)/l).*(-1+exp(b/l)).*(exp(b/l)+exp(a/l)))...
        +...
        ((a < 0) & (b <= a)) .* ...
        l.*(2*-a-l*exp(+(a+b)/l).*(-1+exp(-a/l)).*(exp(-a/l)+exp(-b/l)))...
        +...
        ((b < 0) & (a < b)) .* ...
        l.*(2*-b-l*exp(+(b+a)/l).*(-1+exp(-b/l)).*(exp(-b/l)+exp(-a/l)))...
        +...
        ((a < 0) & (b > 0)) .* ...
        l.*l.*exp(-b/l).*(-1+exp(a/l)).*(-1+exp(b/l))...
        +...
        ((b < 0) & (a > 0)) .* ...
        l.*l.*exp(-a/l).*(-1+exp(b/l)).*(-1+exp(a/l));
    K = K * sf2;
    %if (~dg) & (xeqz)
    %    K = K + K' - diag(diag(K));
    %end
else                                                               % derivatives
  if i == 1
    K = ((a > 0) & (b >= a)) .* ...
        l.*exp(-(a+b)/l).*(-b.*exp(a/l).*(-1+exp(a/l))+exp(2*a/l).*(a-2.*l)+exp(b/l).*(a+2.*l)+2.*exp(a/l).*(l+exp(b/l).*(a-l)))...
        +...
        ((a < 0) & (b <= a)) .* ...
        l.*exp(+(a+b)/l).*(b.*exp(-a/l).*(-1+exp(-a/l))+exp(-2*a/l).*(-a-2.*l)+exp(-b/l).*(-a+2.*l)+2.*exp(-a/l).*(l+exp(-b/l).*(-a-l)))...
        +...
        ((a < 0) & (b > 0)) .* ...
        l.*exp(-b/l).*(b-b.*exp(a/l)+(-1+exp(b/l)).*(-a.*exp(a/l)+2.*l.*(-1+exp(a/l))));
    K = K * sf2;
    K = K + K' - diag(diag(K));
  elseif i == 2
    K = ((a > 0) & (b >= a)) .* ...
        l.*(-2+exp(-a/l)+exp(-b/l))...
        +...
        ((a < 0) & (b <= a)) .* ...
        -l.*(-2+exp(a/l)+exp(b/l))...
        +...
        ((a < 0) & (b > 0)) .* ...
        l.*(exp(-b/l)-exp(a/l));
    K = K * sf2;
    K = K + K' - diag(diag(K));
  elseif i == 3
    K = ((a > 0) & (b >= a)) .* ...
        l.*(2*a-l*exp(-(a+b)/l).*(-1+exp(a/l)).*(exp(a/l)+exp(b/l)))...
        +...
        ((a < 0) & (b <= a)) .* ...
        l.*(2*-a-l*exp(+(a+b)/l).*(-1+exp(-a/l)).*(exp(-a/l)+exp(-b/l)))...
        +...
        ((a < 0) & (b > 0)) .* ...
        l.*l.*exp(-b/l).*(-1+exp(a/l)).*(-1+exp(b/l));
    K = K * sf2 * 2;
    K = K + K' - diag(diag(K)); 
  else
    error('Unknown hyperparameter')
  end
end
end