function K = covIMT3(hyp, x, z, i)

% Integrated MT3
%
% k(x,y) = xxx
%
% where the hyperparameters are:
%
% hyp = [ log(l)
%         location ]
%
% Copyright (c) by James Robert Lloyd, 2013-08-05.

%%%% Warning - assumes 1d x and z

if nargin<2, K = '3'; return; end                  % report number of parameters
if nargin<3, z = []; end                                   % make sure, z exists
xeqz = numel(z)==0; dg = strcmp(z,'diag') && numel(z)>0;        % determine mode

n = size(x,1);
l = exp(hyp(1));
location = hyp(2);
sf2 = exp(2*hyp(3));

if dg
    a = x - location;
    b = x - location;
else
    if xeqz 
        a = repmat(x - location, 1, n);
        b = a';
    else
        a = repmat(x - location, 1, length(z));
        b = repmat((z - location)', length(x), 1);
    end
end

if nargin<4                                                        % covariances
    %%%% TODO - These calculations can be made considerably faster
%     K = ((a > 0) & (b >= a)) .* ...
%         (l/sqrt(3)).*(4*a-sqrt(3)*l+exp(sqrt(3)*(a-b)/l).*(a-b-sqrt(3)*l)+exp(-sqrt(3)*a/l).*(a+sqrt(3)*l)+exp(-sqrt(3)*b/l).*(b+sqrt(3)*l))...
%         +...
%         ((b > 0) & (a > b)) .* ...
%         (l/sqrt(3)).*(4*b-sqrt(3)*l+exp(sqrt(3)*(b-a)/l).*(b-a-sqrt(3)*l)+exp(-sqrt(3)*a/l).*(a+sqrt(3)*l)+exp(-sqrt(3)*b/l).*(b+sqrt(3)*l))...
%         +...
%         ((a < 0) & (b <= a)) .* ...
%         (l/sqrt(3)).*(4*-a-sqrt(3)*l+exp(sqrt(3)*(-a+b)/l).*(-a+b-sqrt(3)*l)+exp(sqrt(3)*a/l).*(-a+sqrt(3)*l)+exp(sqrt(3)*b/l).*(-b+sqrt(3)*l))...
%         +...
%         ((b < 0) & (a < b)) .* ...
%         (l/sqrt(3)).*(4*-b-sqrt(3)*l+exp(sqrt(3)*(-b+a)/l).*(-b+a-sqrt(3)*l)+exp(sqrt(3)*a/l).*(-a+sqrt(3)*l)+exp(sqrt(3)*b/l).*(-b+sqrt(3)*l))...
%         +...
%         ((a < 0) & (b > 0)) .* ...
%         (l/sqrt(3)).*(-sqrt(3)*l+exp(sqrt(3)*(a-b)/l).*(a-b-sqrt(3)*l)+exp(sqrt(3)*a/l).*(-a+sqrt(3)*l)+exp(-sqrt(3)*b/l).*(b+sqrt(3)*l))...
%         +...
%         ((b < 0) & (a > 0)) .* ...
%         (l/sqrt(3)).*(-sqrt(3)*l+exp(sqrt(3)*(b-a)/l).*(b-a-sqrt(3)*l)+exp(sqrt(3)*b/l).*(-b+sqrt(3)*l)+exp(-sqrt(3)*a/l).*(a+sqrt(3)*l));
    eab = exp(sqrt(3)*(a-b)/l);
    eba = 1 ./ eab;
    ea  = exp(sqrt(3)*a/l);
    eb  = exp(sqrt(3)*b/l);
    ema = 1 ./ ea;
    emb = 1 ./ eb;
    K = ((a > 0) & (b >= a)) .* ...
        (l/sqrt(3)).*(4*a-sqrt(3)*l+eab.*(a-b-sqrt(3)*l)+ema.*(a+sqrt(3)*l)+emb.*(b+sqrt(3)*l))...
        +...
        ((b > 0) & (a > b)) .* ...
        (l/sqrt(3)).*(4*b-sqrt(3)*l+eba.*(b-a-sqrt(3)*l)+ema.*(a+sqrt(3)*l)+emb.*(b+sqrt(3)*l))...
        +...
        ((a < 0) & (b <= a)) .* ...
        (l/sqrt(3)).*(4*-a-sqrt(3)*l+eba.*(-a+b-sqrt(3)*l)+ea.*(-a+sqrt(3)*l)+eb.*(-b+sqrt(3)*l))...
        +...
        ((b < 0) & (a < b)) .* ...
        (l/sqrt(3)).*(4*-b-sqrt(3)*l+eab.*(-b+a-sqrt(3)*l)+ea.*(-a+sqrt(3)*l)+eb.*(-b+sqrt(3)*l))...
        +...
        ((a < 0) & (b > 0)) .* ...
        (l/sqrt(3)).*(-sqrt(3)*l+eab.*(a-b-sqrt(3)*l)+ea.*(-a+sqrt(3)*l)+emb.*(b+sqrt(3)*l))...
        +...
        ((b < 0) & (a > 0)) .* ...
        (l/sqrt(3)).*(-sqrt(3)*l+eba.*(b-a-sqrt(3)*l)+eb.*(-b+sqrt(3)*l)+ema.*(a+sqrt(3)*l));
    K = K * sf2;
else                                                               % derivatives
  if i == 1
%     K = ((a > 0) & (b >= a)) .* ...
%         ((4*a*l/sqrt(3))-2*l*l+exp(sqrt(3)*(a-b)/l).*(-a.*a+2*a.*b-b.*b+(4*a*l/sqrt(3))-(4*b*l/sqrt(3))-2*l*l)+exp(-sqrt(3)*a/l).*(a.*a+(4*a*l/sqrt(3))+2*l*l)+exp(-sqrt(3)*b/l).*(b.*b+(4*b*l/sqrt(3))+2*l*l))...
%         +...
%         ((b > 0) & (a > b)) .* ...
%         ((4*b*l/sqrt(3))-2*l*l+exp(sqrt(3)*(b-a)/l).*(-a.*a+2*a.*b-b.*b+(4*b*l/sqrt(3))-(4*a*l/sqrt(3))-2*l*l)+exp(-sqrt(3)*a/l).*(a.*a+(4*a*l/sqrt(3))+2*l*l)+exp(-sqrt(3)*b/l).*(b.*b+(4*b*l/sqrt(3))+2*l*l))...
%         +...
%         ((a < 0) & (b <= a)) .* ...
%         ((4*-a*l/sqrt(3))-2*l*l+exp(sqrt(3)*(-a+b)/l).*(-a.*a+2*a.*b-b.*b+(4*-a*l/sqrt(3))-(4*-b*l/sqrt(3))-2*l*l)+exp(-sqrt(3)*-a/l).*(a.*a+(4*-a*l/sqrt(3))+2*l*l)+exp(sqrt(3)*b/l).*(b.*b+(4*-b*l/sqrt(3))+2*l*l))...
%         +...
%         ((b < 0) & (a < b)) .* ...
%         ((4*-b*l/sqrt(3))-2*l*l+exp(sqrt(3)*(-b+a)/l).*(-a.*a+2*a.*b-b.*b+(4*-b*l/sqrt(3))-(4*-a*l/sqrt(3))-2*l*l)+exp(-sqrt(3)*-a/l).*(a.*a+(4*-a*l/sqrt(3))+2*l*l)+exp(sqrt(3)*b/l).*(b.*b+(4*-b*l/sqrt(3))+2*l*l))...
%         +...
%         ((a < 0) & (b > 0)) .* ...
%         (-2*l*l+exp(sqrt(3)*(a-b)/l).*(-a.*a+2*a.*b-b.*b+(4*a*l/sqrt(3))-(4*b*l/sqrt(3))-2*l*l)+exp(sqrt(3)*a/l).*(a.*a-(4*a*l/sqrt(3))+2*l*l)+exp(-sqrt(3)*b/l).*(b.*b+(4*b*l/sqrt(3))+2*l*l))...
%         +...
%         ((b < 0) & (a > 0)) .* ...
%         (-2*l*l+exp(sqrt(3)*(b-a)/l).*(-a.*a+2*a.*b-b.*b+(4*b*l/sqrt(3))-(4*a*l/sqrt(3))-2*l*l)+exp(sqrt(3)*b/l).*(b.*b-(4*b*l/sqrt(3))+2*l*l)+exp(-sqrt(3)*a/l).*(a.*a+(4*a*l/sqrt(3))+2*l*l));
    eab = exp(sqrt(3)*(a-b)/l);
    eba = 1 ./ eab;
    ea  = exp(sqrt(3)*a/l);
    eb  = exp(sqrt(3)*b/l);
    ema = 1 ./ ea;
    emb = 1 ./ eb; 
    aa = a.*a;
    ab = a.*b;
    bb = b.*b;
    K = ((a > 0) & (b >= a)) .* ...
        ((4*a*l/sqrt(3))-2*l*l+eab.*(-aa+2*ab-bb+(4*a*l/sqrt(3))-(4*b*l/sqrt(3))-2*l*l)+ema.*(aa+(4*a*l/sqrt(3))+2*l*l)+emb.*(bb+(4*b*l/sqrt(3))+2*l*l))...
        +...
        ((b > 0) & (a > b)) .* ...
        ((4*b*l/sqrt(3))-2*l*l+eba.*(-aa+2*ab-bb+(4*b*l/sqrt(3))-(4*a*l/sqrt(3))-2*l*l)+ema.*(aa+(4*a*l/sqrt(3))+2*l*l)+emb.*(bb+(4*b*l/sqrt(3))+2*l*l))...
        +...
        ((a < 0) & (b <= a)) .* ...
        ((4*-a*l/sqrt(3))-2*l*l+eba.*(-aa+2*ab-bb+(4*-a*l/sqrt(3))-(4*-b*l/sqrt(3))-2*l*l)+ea.*(aa+(4*-a*l/sqrt(3))+2*l*l)+eb.*(bb+(4*-b*l/sqrt(3))+2*l*l))...
        +...
        ((b < 0) & (a < b)) .* ...
        ((4*-b*l/sqrt(3))-2*l*l+eab.*(-aa+2*ab-bb+(4*-b*l/sqrt(3))-(4*-a*l/sqrt(3))-2*l*l)+ea.*(aa+(4*-a*l/sqrt(3))+2*l*l)+eb.*(bb+(4*-b*l/sqrt(3))+2*l*l))...
        +...
        ((a < 0) & (b > 0)) .* ...
        (-2*l*l+eab.*(-aa+2*ab-bb+(4*a*l/sqrt(3))-(4*b*l/sqrt(3))-2*l*l)+ea.*(aa-(4*a*l/sqrt(3))+2*l*l)+emb.*(bb+(4*b*l/sqrt(3))+2*l*l))...
        +...
        ((b < 0) & (a > 0)) .* ...
        (-2*l*l+eba.*(-aa+2*ab-bb+(4*b*l/sqrt(3))-(4*a*l/sqrt(3))-2*l*l)+eb.*(bb-(4*b*l/sqrt(3))+2*l*l)+ema.*(aa+(4*a*l/sqrt(3))+2*l*l));
    K = K * sf2;
  elseif i == 2
%     K = ((a > 0) & (b >= a)) .* ...
%         (1/sqrt(3)).*(-4*l+exp(-sqrt(3)*a/l).*(sqrt(3)*a+2*l)+exp(-sqrt(3)*b/l).*(sqrt(3)*b+2*l))...
%         +...
%         ((b > 0) & (a > b)) .* ...
%         (1/sqrt(3)).*(-4*l+exp(-sqrt(3)*a/l).*(sqrt(3)*a+2*l)+exp(-sqrt(3)*b/l).*(sqrt(3)*b+2*l))...
%         +...
%         ((a < 0) & (b <= a)) .* ...
%         -(1/sqrt(3)).*(-4*l+exp(sqrt(3)*a/l).*(-sqrt(3)*a+2*l)+exp(sqrt(3)*b/l).*(-sqrt(3)*b+2*l))...
%         +...
%         ((b < 0) & (a < b)) .* ...
%         -(1/sqrt(3)).*(-4*l+exp(sqrt(3)*a/l).*(-sqrt(3)*a+2*l)+exp(sqrt(3)*b/l).*(-sqrt(3)*b+2*l))...
%         +...
%         ((a < 0) & (b > 0)) .* ...
%         (1/sqrt(3)).*(exp(sqrt(3)*a/l).*(sqrt(3)*a-2*l)+exp(-sqrt(3)*b/l).*(sqrt(3)*b+2*l))...
%         +...
%         ((b < 0) & (a > 0)) .* ...
%         (1/sqrt(3)).*(exp(sqrt(3)*b/l).*(sqrt(3)*b-2*l)+exp(-sqrt(3)*a/l).*(sqrt(3)*a+2*l));=
    ea  = exp(sqrt(3)*a/l);
    eb  = exp(sqrt(3)*b/l);
    ema = 1 ./ ea;
    emb = 1 ./ eb;
    K = ((a > 0) & (b >= a)) .* ...
        (1/sqrt(3)).*(-4*l+ema.*(sqrt(3)*a+2*l)+emb.*(sqrt(3)*b+2*l))...
        +...
        ((b > 0) & (a > b)) .* ...
        (1/sqrt(3)).*(-4*l+ema.*(sqrt(3)*a+2*l)+emb.*(sqrt(3)*b+2*l))...
        +...
        ((a < 0) & (b <= a)) .* ...
        -(1/sqrt(3)).*(-4*l+ea.*(-sqrt(3)*a+2*l)+eb.*(-sqrt(3)*b+2*l))...
        +...
        ((b < 0) & (a < b)) .* ...
        -(1/sqrt(3)).*(-4*l+ea.*(-sqrt(3)*a+2*l)+eb.*(-sqrt(3)*b+2*l))...
        +...
        ((a < 0) & (b > 0)) .* ...
        (1/sqrt(3)).*(ea.*(sqrt(3)*a-2*l)+emb.*(sqrt(3)*b+2*l))...
        +...
        ((b < 0) & (a > 0)) .* ...
        (1/sqrt(3)).*(eb.*(sqrt(3)*b-2*l)+ema.*(sqrt(3)*a+2*l));
    K = K * sf2;
  elseif i == 3
%     K = ((a > 0) & (b >= a)) .* ...
%         (l/sqrt(3)).*(4*a-sqrt(3)*l+exp(sqrt(3)*(a-b)/l).*(a-b-sqrt(3)*l)+exp(-sqrt(3)*a/l).*(a+sqrt(3)*l)+exp(-sqrt(3)*b/l).*(b+sqrt(3)*l))...
%         +...
%         ((b > 0) & (a > b)) .* ...
%         (l/sqrt(3)).*(4*b-sqrt(3)*l+exp(sqrt(3)*(b-a)/l).*(b-a-sqrt(3)*l)+exp(-sqrt(3)*a/l).*(a+sqrt(3)*l)+exp(-sqrt(3)*b/l).*(b+sqrt(3)*l))...
%         +...
%         ((a < 0) & (b <= a)) .* ...
%         (l/sqrt(3)).*(4*-a-sqrt(3)*l+exp(sqrt(3)*(-a+b)/l).*(-a+b-sqrt(3)*l)+exp(sqrt(3)*a/l).*(-a+sqrt(3)*l)+exp(sqrt(3)*b/l).*(-b+sqrt(3)*l))...
%         +...
%         ((b < 0) & (a < b)) .* ...
%         (l/sqrt(3)).*(4*-b-sqrt(3)*l+exp(sqrt(3)*(-b+a)/l).*(-b+a-sqrt(3)*l)+exp(sqrt(3)*a/l).*(-a+sqrt(3)*l)+exp(sqrt(3)*b/l).*(-b+sqrt(3)*l))...
%         +...
%         ((a < 0) & (b > 0)) .* ...
%         (l/sqrt(3)).*(-sqrt(3)*l+exp(sqrt(3)*(a-b)/l).*(a-b-sqrt(3)*l)+exp(sqrt(3)*a/l).*(-a+sqrt(3)*l)+exp(-sqrt(3)*b/l).*(b+sqrt(3)*l))...
%         +...
%         ((b < 0) & (a > 0)) .* ...
%         (l/sqrt(3)).*(-sqrt(3)*l+exp(sqrt(3)*(b-a)/l).*(b-a-sqrt(3)*l)+exp(sqrt(3)*b/l).*(-b+sqrt(3)*l)+exp(-sqrt(3)*a/l).*(a+sqrt(3)*l));
    eab = exp(sqrt(3)*(a-b)/l);
    eba = 1 ./ eab;
    ea  = exp(sqrt(3)*a/l);
    eb  = exp(sqrt(3)*b/l);
    ema = 1 ./ ea;
    emb = 1 ./ eb;
    K = ((a > 0) & (b >= a)) .* ...
        (l/sqrt(3)).*(4*a-sqrt(3)*l+eab.*(a-b-sqrt(3)*l)+ema.*(a+sqrt(3)*l)+emb.*(b+sqrt(3)*l))...
        +...
        ((b > 0) & (a > b)) .* ...
        (l/sqrt(3)).*(4*b-sqrt(3)*l+eba.*(b-a-sqrt(3)*l)+ema.*(a+sqrt(3)*l)+emb.*(b+sqrt(3)*l))...
        +...
        ((a < 0) & (b <= a)) .* ...
        (l/sqrt(3)).*(4*-a-sqrt(3)*l+eba.*(-a+b-sqrt(3)*l)+ea.*(-a+sqrt(3)*l)+eb.*(-b+sqrt(3)*l))...
        +...
        ((b < 0) & (a < b)) .* ...
        (l/sqrt(3)).*(4*-b-sqrt(3)*l+eab.*(-b+a-sqrt(3)*l)+ea.*(-a+sqrt(3)*l)+eb.*(-b+sqrt(3)*l))...
        +...
        ((a < 0) & (b > 0)) .* ...
        (l/sqrt(3)).*(-sqrt(3)*l+eab.*(a-b-sqrt(3)*l)+ea.*(-a+sqrt(3)*l)+emb.*(b+sqrt(3)*l))...
        +...
        ((b < 0) & (a > 0)) .* ...
        (l/sqrt(3)).*(-sqrt(3)*l+eba.*(b-a-sqrt(3)*l)+eb.*(-b+sqrt(3)*l)+ema.*(a+sqrt(3)*l));
    K = K * sf2 * 2;
  else
    error('Unknown hyperparameter')
  end
end
end